spring:
  application:
    name: messaging-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/messagingdb
    username: postgres
    password: ${DB_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: messaging-group
      auto-offset-reset: earliest
server:
  port: 8082
