spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: chat-service
          uri: http://localhost:8084
          predicates:
            - Path=/chat/**
        - id: messaging-service
          uri: http://localhost:8082
          predicates:
            - Path=/messages/**
        - id: notification-service
          uri: ws://localhost:8081
          predicates:
            - Path=/ws/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080
